### ISSUE TITLE
GitLab requires "severity" field now

### ISSUE THREAD

**Issue by topschrott** [awelzel/flake8-gl-codeclimate#2]
Current versions of GitLab (12.9+?) seem to require the severity field within the code climate JSON report.

https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#code-quality-reports

When not supplied, the output looks like this:
![image](https://user-images.githubusercontent.com/25614879/139687093-e67bb6c6-f0d4-4076-8e76-44efc169ddd2.png)

`flake8` does not seem to report a severity, so defaulting it to a fixed value might be the only option? E.g.:
```
"severity" : "minor",
```

**Comment by awelzel** [comment]
Closed via #4 .
