### ISSUE TITLE
JSON file must contain severity keyword

### ISSUE THREAD

**Issue by justinTM** [awelzel/flake8-gl-codeclimate#3]
Current:
<p style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; caret-color: rgb(64, 64, 64); color: rgb(64, 64, 64); font-family: -apple-system, BlinkMacSystemFont, &quot;segoe ui&quot;, Roboto, &quot;noto sans&quot;, Ubuntu, Cantarell, &quot;helvetica neue&quot;, sans-serif, &quot;apple color emoji&quot;, &quot;segoe ui emoji&quot;, &quot;segoe ui symbol&quot;, &quot;noto color emoji&quot;; text-align: left;">The Code Quality report artifact JSON file must contain an array of objects with the following properties:</p>

Name | Description
-- | --
✅ description | A description of the code quality violation.
✅ fingerprint | A unique fingerprint to identify the code quality violation. For example, an MD5 hash.
❌ severity | A severity string (can be info, minor, major, critical, or blocker).
✅ location.path | The relative path to the file containing the code quality violation.
✅ location.lines.begin or location.positions.begin.line | The line on which the code quality violation occurred.

https://github.com/awelzel/flake8-gl-codeclimate/blob/4eaaf623747ca2c76700951a692e12781aaffb65/flake8_gl_codeclimate/__init__.py#L101

**Comment by awelzel** [comment]
Closed via #4 .
